# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4abb85f0a7fe7de245f8f2baa38e8057a7381034a6edc30c2d44e10df2abf3f8d4605f1396bf974c336b96ff672e92a798d6c4d9135fcdde32b15f44e302283

test:
  secret_key_base: f5e3936024a60298e41a869b5b13d247baf5a230e4ab7ee48cd4b0e309cafe282a0e075f801ba6ce0c635becdd8df2fb6a91b33d4457dfc3e6e297f9bf212b04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
